CREATE TABLE CRUISE.USERS(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT COLLATE UTF8_GENERAL_CI NOT NULL,
    EMAIL VARCHAR(255),
    MATCHER VARCHAR(255),
    EMAILME BOOLEAN DEFAULT FALSE,
    ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    DISPLAYNAME VARCHAR(255)
);

CREATE TABLE CRUISE.properties(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    buildId BIGINT,
    `key` VARCHAR(255),
    value VARCHAR(255)
);

CREATE INDEX IDX_PROPERTIES_KEY ON CRUISE.properties(`key`);
CREATE INDEX IDX_PROPERTIES_BUILDID ON CRUISE.properties(buildId);

CREATE TABLE CRUISE.artifactPlans(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    buildId BIGINT,
    src VARCHAR(255),
    dest VARCHAR(255),
    artifactType VARCHAR(255)
);

CREATE TABLE CRUISE.resources(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    buildId BIGINT NOT NULL
);
CREATE INDEX IDX_RESOURCES_BUILDID ON CRUISE.resources(buildId);

CREATE TABLE CRUISE.versioninfos(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    componentName VARCHAR(255) NOT NULL UNIQUE,
    installedVersion VARCHAR(100) NOT NULL,
    latestVersion VARCHAR(50),
    latestVersionUpdatedAt TIMESTAMP
);

CREATE TABLE CRUISE.pipelines(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name TEXT COLLATE UTF8_GENERAL_CI,
    buildCauseType VARCHAR(255),
    buildCauseBy VARCHAR(255),
    label VARCHAR(255),
    buildCauseMessage LONGTEXT,
    counter BIGINT,
    locked BOOLEAN DEFAULT FALSE NOT NULL,
    naturalOrder DOUBLE DEFAULT 0.0 NOT NULL,
    comment TEXT
);
CREATE INDEX IDX_PIPELINE_NAME ON CRUISE.pipelines(NAME(255));
CREATE INDEX IDX_PIPELINE_LABEL ON CRUISE.pipelines(LABEL);
CREATE INDEX IDX_PIPELINES_NAME_COUNTER ON CRUISE.pipelines(NAME(255), COUNTER);
CREATE INDEX IDX_PIPELINES_LOCKED ON CRUISE.pipelines(LOCKED);

CREATE TABLE CRUISE.stages(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name TEXT COLLATE UTF8_GENERAL_CI,
    approvedBy VARCHAR(255),
    pipelineId BIGINT,
    createdTime TIMESTAMP,
    orderId INTEGER NOT NULL,
    RESULT VARCHAR(50) DEFAULT 'Unknown' NOT NULL,
    APPROVALTYPE VARCHAR(255),
    COUNTER INTEGER NOT NULL,
    COMPLETEDBYTRANSITIONID BIGINT,
    STATE VARCHAR(50) DEFAULT 'Unknown' NOT NULL,
    LATESTRUN BOOLEAN DEFAULT FALSE NOT NULL,
    FETCHMATERIALS BOOLEAN DEFAULT TRUE NOT NULL,
    CLEANWORKINGDIR BOOLEAN DEFAULT FALSE NOT NULL,
    RERUNOFCOUNTER INT,
    ARTIFACTSDELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CONFIGVERSION VARCHAR(255),
    LASTTRANSITIONEDTIME TIMESTAMP
);
CREATE INDEX IDX_STAGES_PIPELINEID ON CRUISE.STAGES(PIPELINEID);
CREATE INDEX IDX_STAGE_NAME ON CRUISE.STAGES(NAME(255));
CREATE INDEX IDX_STAGES_ORDERID ON CRUISE.STAGES(ORDERID);
CREATE INDEX IDX_STAGES_NAME_PIPELINEID ON CRUISE.STAGES(NAME(255), PIPELINEID);
CREATE INDEX IDX_STAGES_COUNTER_INDEX ON CRUISE.STAGES(COUNTER);
CREATE INDEX IDX_STAGES_COMPLETEDBYTRANSITIONID ON CRUISE.STAGES(COMPLETEDBYTRANSITIONID DESC);
CREATE INDEX IDX_STAGES_STATE ON CRUISE.STAGES(STATE);
CREATE INDEX IDX_STAGES_NAME_LATESTRUN_RESULT ON CRUISE.STAGES(NAME(255), LATESTRUN, RESULT);


CREATE VIEW CRUISE._STAGES(ID, NAME, APPROVEDBY, PIPELINEID, CREATEDTIME, ORDERID, RESULT, APPROVALTYPE, COUNTER, COMPLETEDBYTRANSITIONID, STATE, LATESTRUN, FETCHMATERIALS, CLEANWORKINGDIR, RERUNOFCOUNTER, ARTIFACTSDELETED, CONFIGVERSION, LASTTRANSITIONEDTIME, PIPELINENAME, BUILDCAUSETYPE, BUILDCAUSEBY, PIPELINELABEL, BUILDCAUSEMESSAGE, PIPELINECOUNTER, LOCKED, NATURALORDER) AS
SELECT
    S.ID,
    S.NAME,
    S.APPROVEDBY,
    S.PIPELINEID,
    S.CREATEDTIME,
    S.ORDERID,
    S.RESULT,
    S.APPROVALTYPE,
    S.COUNTER,
    S.COMPLETEDBYTRANSITIONID,
    S.STATE,
    S.LATESTRUN,
    S.FETCHMATERIALS,
    S.CLEANWORKINGDIR,
    S.RERUNOFCOUNTER,
    S.ARTIFACTSDELETED,
    S.CONFIGVERSION,
    S.LASTTRANSITIONEDTIME,
    P.NAME AS PIPELINENAME,
    P.BUILDCAUSETYPE,
    P.BUILDCAUSEBY,
    P.LABEL AS PIPELINELABEL,
    P.BUILDCAUSEMESSAGE,
    P.COUNTER AS PIPELINECOUNTER,
    P.LOCKED,
    P.NATURALORDER
FROM CRUISE.PIPELINES P
    /* CRUISE.PIPELINES.tableScan */
INNER JOIN CRUISE.STAGES S
    /* IDX_STAGES_PIPELINEID: PIPELINEID = P.ID */
    ON 1=1
WHERE P.ID = S.PIPELINEID;


CREATE TABLE CRUISE.STAGEARTIFACTCLEANUPPROHIBITED(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    STAGENAME TEXT COLLATE UTF8_GENERAL_CI NOT NULL,
    PIPELINENAME TEXT COLLATE UTF8_GENERAL_CI NOT NULL,
    PROHIBITED BOOLEAN DEFAULT FALSE NOT NULL
);
CREATE INDEX IDX_STAGEARTIFACTCLEANUPPROHIBITED_PIPELINENAME ON CRUISE.STAGEARTIFACTCLEANUPPROHIBITED(PIPELINENAME(255));

CREATE TABLE CRUISE.BUILDCAUSEBUFFER(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PIPELINENAME VARCHAR(255),
    BUILDCAUSE BINARY,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE CRUISE.PIPELINEMATERIALREVISIONS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FOLDER VARCHAR(255),
    NAME VARCHAR(255),
    PIPELINEID BIGINT NOT NULL,
    TOREVISIONID BIGINT NOT NULL,
    FROMREVISIONID BIGINT NOT NULL,
    CHANGED BOOLEAN DEFAULT FALSE,
    MATERIALID BIGINT,
    ACTUALFROMREVISIONID BIGINT NOT NULL
);
CREATE INDEX IDX_PMR_PIPELINE_ID ON CRUISE.PIPELINEMATERIALREVISIONS(PIPELINEID);

CREATE TABLE CRUISE.NOTIFICATIONFILTERS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERID BIGINT,
    PIPELINE VARCHAR(255),
    STAGE VARCHAR(255),
    EVENT VARCHAR(50),
    MYCHECKIN BOOLEAN
);

CREATE TABLE CRUISE.ARTIFACTPROPERTIESGENERATOR(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    JOBID BIGINT,
    NAME VARCHAR(255),
    SRC VARCHAR(512),
    XPATH VARCHAR(512),
    REGEX VARCHAR(512),
    GENERATORTYPE VARCHAR(255)
);
CREATE INDEX IDX_ARTIFACTPROPERTIESGENERATOR_JOBID ON CRUISE.ARTIFACTPROPERTIESGENERATOR(JOBID);

CREATE TABLE CRUISE.BUILDS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT COLLATE UTF8_GENERAL_CI,
    STATE VARCHAR(50),
    RESULT VARCHAR(50),
    AGENTUUID VARCHAR(50),
    SCHEDULEDDATE TIMESTAMP,
    STAGEID BIGINT,
    IGNORED BOOLEAN DEFAULT FALSE,
    RUNONALLAGENTS BOOLEAN DEFAULT FALSE,
    ORIGINALJOBID BIGINT,
    RERUN BOOLEAN DEFAULT FALSE NOT NULL,
    RUNMULTIPLEINSTANCE BOOLEAN DEFAULT FALSE
);
CREATE INDEX IDX_BUILD_STATE ON CRUISE.BUILDS(STATE);
CREATE INDEX IDX_BUILD_NAME ON CRUISE.BUILDS(NAME(255));
CREATE INDEX IDX_BUILD_RESULT ON CRUISE.BUILDS(RESULT);
CREATE INDEX IDX_BUILD_AGENT ON CRUISE.BUILDS(AGENTUUID);
CREATE INDEX IDX_BUILD_IGNORED ON CRUISE.BUILDS(IGNORED);
CREATE INDEX IDX_BUILDS_AGENTID_STAGEID_NAME ON CRUISE.BUILDS(NAME(255), AGENTUUID, STAGEID, STATE, RESULT);
CREATE INDEX IDX_BUILDS_NAME_STATE_STAGEID ON CRUISE.BUILDS(NAME(255), STATE, STAGEID);
CREATE INDEX IDX_BUILDS_NAME_STAGE_ID ON CRUISE.BUILDS(NAME(255), STAGEID);
CREATE INDEX IDX_BUILDS_STAGEID ON CRUISE.BUILDS(STAGEID);


CREATE VIEW CRUISE._BUILDS(ID, NAME, STATE, RESULT, AGENTUUID, SCHEDULEDDATE, STAGEID, IGNORED, RUNONALLAGENTS, ORIGINALJOBID, RERUN, RUNMULTIPLEINSTANCE, PIPELINEID, PIPELINENAME, PIPELINELABEL, PIPELINECOUNTER, STAGENAME, STAGECOUNTER, FETCHMATERIALS, CLEANWORKINGDIR, RERUNOFCOUNTER) AS
SELECT
    B.ID,
    B.NAME,
    B.STATE,
    B.RESULT,
    B.AGENTUUID,
    B.SCHEDULEDDATE,
    B.STAGEID,
    B.IGNORED,
    B.RUNONALLAGENTS,
    B.ORIGINALJOBID,
    B.RERUN,
    B.RUNMULTIPLEINSTANCE,
    P.ID AS PIPELINEID,
    P.NAME AS PIPELINENAME,
    P.LABEL AS PIPELINELABEL,
    P.COUNTER AS PIPELINECOUNTER,
    S.NAME AS STAGENAME,
    S.COUNTER AS STAGECOUNTER,
    S.FETCHMATERIALS,
    S.CLEANWORKINGDIR,
    S.RERUNOFCOUNTER
FROM CRUISE.PIPELINES P
    /* CRUISE.PIPELINES.tableScan */
INNER JOIN CRUISE.STAGES S
    /* IDX_STAGES_PIPELINEID: PIPELINEID = P.ID */
    ON 1=1
    /* WHERE P.ID = S.PIPELINEID
    */
INNER JOIN CRUISE.BUILDS B
    /* IDX_BUILDS_STAGEID: STAGEID = S.ID */
    ON 1=1
WHERE (P.ID = S.PIPELINEID)
    AND (S.ID = B.STAGEID);

CREATE TABLE CRUISE.PLUGINS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PLUGINID VARCHAR(255) NOT NULL,
    CONFIGURATION TEXT
);

CREATE TABLE CRUISE.MODIFIEDFILES(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FILENAME VARCHAR(1024),
    REVISION VARCHAR(50),
    FOLDERNAME VARCHAR(512),
    ACTION VARCHAR(50),
    MODIFICATIONID BIGINT NOT NULL
);

CREATE TABLE CRUISE.GADGETOAUTHCLIENTS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OAUTHAUTHORIZEURL VARCHAR(255) NOT NULL,
    CLIENTID VARCHAR(255) NOT NULL,
    CLIENTSECRET VARCHAR(255) NOT NULL,
    SERVICENAME VARCHAR(255) NOT NULL
);

CREATE TABLE CRUISE.MODIFICATIONS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(255),
    USERNAME VARCHAR(255),
    COMMENT LONGTEXT,
    EMAILADDRESS VARCHAR(255),
    REVISION VARCHAR(1024),
    MODIFIEDTIME TIMESTAMP,
    FROMEXTERNAL BOOLEAN DEFAULT FALSE,
    MATERIALID BIGINT,
    PIPELINELABEL VARCHAR(255),
    PIPELINEID BIGINT,
    ADDITIONALDATA TEXT
);
CREATE INDEX IDX_MODIFICATIONS_MODIFIEDTIME ON CRUISE.MODIFICATIONS(MODIFIEDTIME);
CREATE INDEX IDX_MOD_NEW_MATERIAL_ID ON CRUISE.MODIFICATIONS(MATERIALID);
CREATE INDEX IDX_MODIFICATIONS_MATERIALID_ID ON CRUISE.MODIFICATIONS(MATERIALID, ID);
CREATE INDEX IDX_MODIFICATIONS_REVISION ON CRUISE.MODIFICATIONS(REVISION(255));


CREATE TABLE CRUISE.BUILDSTATETRANSITIONS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CURRENTSTATE VARCHAR(255) NOT NULL,
    STATECHANGETIME TIMESTAMP NOT NULL,
    BUILDID BIGINT NOT NULL,
    STAGEID BIGINT
);
CREATE INDEX IDX_STATE_TRANSITION ON CRUISE.BUILDSTATETRANSITIONS(CURRENTSTATE);
CREATE INDEX IDX_BST_BUILDID_CURRENTSTATE ON CRUISE.BUILDSTATETRANSITIONS(BUILDID, CURRENTSTATE);

CREATE TABLE CRUISE.PREFFERED(
    id BIGINT,
    IN_NAME TEXT COLLATE UTF8_GENERAL_CI
);

CREATE TABLE CRUISE.AGENTS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID VARCHAR(40) NOT NULL,
    COOKIE VARCHAR(40) NOT NULL
);

CREATE TABLE CRUISE.PIPELINELABELCOUNTS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PIPELINENAME VARCHAR(255),
    LABELCOUNT BIGINT,
    PAUSE_CAUSE VARCHAR(255),
    PAUSE_BY VARCHAR(255),
    PAUSED BOOLEAN DEFAULT FALSE
);
CREATE INDEX IDX_PIPELINELABELCOUNTS_PIPELINENAME ON CRUISE.PIPELINELABELCOUNTS(PIPELINENAME);

CREATE TABLE CRUISE.MATERIALS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(255),
    URL TEXT,
    USERNAME VARCHAR(255),
    CHECKEXTERNALS BOOLEAN DEFAULT FALSE,
    PIPELINENAME VARCHAR(255),
    STAGENAME VARCHAR(255),
    VIEW TEXT,
    BRANCH TEXT,
    SUBMODULEFOLDER TEXT,
    USETICKETS VARCHAR(10),
    FINGERPRINT CHAR(64) NOT NULL,
    FLYWEIGHTNAME VARCHAR(50) NOT NULL,
    WORKSPACE VARCHAR(255),
    PROJECTPATH VARCHAR(255),
    DOMAIN VARCHAR(255),
    CONFIGURATION TEXT,
    ADDITIONALDATA TEXT
);
CREATE INDEX IDX_MATERIALS_PIPELINENAME ON CRUISE.MATERIALS(PIPELINENAME);

CREATE TABLE CRUISE.OAUTHCLIENTS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CLIENTID VARCHAR(255) NOT NULL,
    CLIENTSECRET VARCHAR(255) NOT NULL,
    REDIRECTURI VARCHAR(255) NOT NULL
);


CREATE TABLE CRUISE.OAUTHAUTHORIZATIONS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERID VARCHAR(255) NOT NULL,
    OAUTHCLIENTID BIGINT,
    CODE VARCHAR(255) NOT NULL,
    EXPIRESAT BIGINT
);

CREATE TABLE CRUISE.OAUTHTOKENS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERID VARCHAR(255) NOT NULL,
    OAUTHCLIENTID BIGINT,
    ACCESSTOKEN VARCHAR(255) NOT NULL,
    REFRESHTOKEN VARCHAR(255) NOT NULL,
    EXPIRESAT BIGINT
);
CREATE TABLE CRUISE.SERVERBACKUPS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PATH VARCHAR(2048),
    TIME TIMESTAMP,
    USERNAME TEXT COLLATE UTF8_GENERAL_CI
);

CREATE TABLE CRUISE.GADGETOAUTHACCESSTOKENS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERID VARCHAR(255) NOT NULL,
    ACCESSTOKEN VARCHAR(255) NOT NULL,
    REFRESHTOKEN VARCHAR(255) NOT NULL,
    GADGETSOAUTHCLIENTID BIGINT NOT NULL,
    EXPIRESIN BIGINT
);

CREATE TABLE CRUISE.GADGETOAUTHAUTHORIZATIONCODES(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERID VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    GADGETSOAUTHCLIENTID BIGINT NOT NULL,
    EXPIRESIN BIGINT
);

CREATE TABLE CRUISE.ENVIRONMENTVARIABLES(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ENTITYID BIGINT,
    VARIABLENAME VARCHAR(255),
    VARIABLEVALUE TEXT,
    ENTITYTYPE VARCHAR(100) NOT NULL,
    ISSECURE BOOLEAN DEFAULT FALSE
);
CREATE INDEX IDX_ENVIRONMENTVARIABLES_ENTITYTYPE ON CRUISE.ENVIRONMENTVARIABLES(ENTITYTYPE);
CREATE INDEX IDX_ENV_JOB_ID ON CRUISE.ENVIRONMENTVARIABLES(ENTITYID);

CREATE TABLE CRUISE.PIPELINESELECTIONS(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SELECTIONS LONGTEXT,
    LASTUPDATE TIMESTAMP,
    USERID BIGINT,
    ISBLACKLIST BOOLEAN DEFAULT TRUE
);

ALTER TABLE PLUGINS ADD CONSTRAINT CONSTRAINT_E72 UNIQUE(PLUGINID);
ALTER TABLE OAUTHCLIENTS ADD CONSTRAINT CONSTRAINT_86 UNIQUE(CLIENTID);
ALTER TABLE OAUTHTOKENS ADD CONSTRAINT CONSTRAINT_BE6 UNIQUE(REFRESHTOKEN);
ALTER TABLE ARTIFACTPROPERTIESGENERATOR ADD CONSTRAINT CONSTRAINT_D09 UNIQUE(JOBID, NAME);
ALTER TABLE OAUTHAUTHORIZATIONS ADD CONSTRAINT CONSTRAINT_F06 UNIQUE(CODE);
ALTER TABLE AGENTS ADD CONSTRAINT CONSTRAINT_72F UNIQUE(UUID);
ALTER TABLE GADGETOAUTHCLIENTS ADD CONSTRAINT CONSTRAINT_801C UNIQUE(SERVICENAME);
ALTER TABLE USERS ADD CONSTRAINT UNIQUE_NAME UNIQUE(NAME(255));
ALTER TABLE PROPERTIES ADD CONSTRAINT CONSTRAINT_E5 UNIQUE(BUILDID, `KEY`);
ALTER TABLE PIPELINELABELCOUNTS ADD CONSTRAINT UNIQUE_PIPELINE_NAME UNIQUE(PIPELINENAME);
ALTER TABLE GADGETOAUTHACCESSTOKENS ADD CONSTRAINT UNIQUE_USER_ID_CLIENT_ID_TOKEN UNIQUE(GADGETSOAUTHCLIENTID, USERID);
ALTER TABLE GADGETOAUTHCLIENTS ADD CONSTRAINT CONSTRAINT_801 UNIQUE(OAUTHAUTHORIZEURL);
ALTER TABLE AGENTS ADD CONSTRAINT CONSTRAINT_72F4 UNIQUE(COOKIE);
ALTER TABLE MATERIALS ADD CONSTRAINT UNIQUE_FINGERPRINT UNIQUE(FINGERPRINT);
ALTER TABLE OAUTHCLIENTS ADD CONSTRAINT UNIQUE_OAUTH_CLIENT_NAME UNIQUE(NAME);
ALTER TABLE BUILDCAUSEBUFFER ADD CONSTRAINT UNIQUE_BUILD_BUFFER_PIPELINE_NAME UNIQUE(PIPELINENAME);


ALTER TABLE OAUTHTOKENS ADD CONSTRAINT CONSTRAINT_BE UNIQUE(ACCESSTOKEN);
ALTER TABLE GADGETOAUTHAUTHORIZATIONCODES ADD CONSTRAINT UNIQUE_USER_ID_CLIENT_ID_CODE UNIQUE(GADGETSOAUTHCLIENTID, USERID);
ALTER TABLE MATERIALS ADD CONSTRAINT MATERIALS_FLYWEIGHTNAME_UNIQUE UNIQUE(FLYWEIGHTNAME);
ALTER TABLE VERSIONINFOS ADD CONSTRAINT CONSTRAINT_848D UNIQUE(COMPONENTNAME);
ALTER TABLE STAGES ADD CONSTRAINT UNIQUE_PIPELINE_ID_NAME_COUNTER UNIQUE(PIPELINEID, NAME(255), COUNTER);
ALTER TABLE ARTIFACTPLANS ADD CONSTRAINT FK_ARTIFACTPLANS_BUILDS FOREIGN KEY(BUILDID) REFERENCES BUILDS(ID) ON DELETE CASCADE;
ALTER TABLE STAGES ADD CONSTRAINT FK_STAGES_PIPELINES FOREIGN KEY(PIPELINEID) REFERENCES PIPELINES(ID) ON DELETE CASCADE;
ALTER TABLE MODIFIEDFILES ADD CONSTRAINT FK_MODIFIEDFILES_MODIFICATIONS FOREIGN KEY(MODIFICATIONID) REFERENCES MODIFICATIONS(ID) ON DELETE CASCADE;
ALTER TABLE OAUTHTOKENS ADD CONSTRAINT FK_OAUTH_TOKEN_OAUTH_CLIENT FOREIGN KEY(OAUTHCLIENTID) REFERENCES OAUTHCLIENTS(ID);
ALTER TABLE PIPELINESELECTIONS ADD CONSTRAINT FK_PIPELINESELECTIONS_USERID FOREIGN KEY(USERID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE ARTIFACTPROPERTIESGENERATOR ADD CONSTRAINT FK_ARTIFACTPROPERTIESGENERATOR_JOBS FOREIGN KEY(JOBID) REFERENCES BUILDS(ID) ON DELETE CASCADE;

ALTER TABLE PIPELINEMATERIALREVISIONS ADD CONSTRAINT FK_PMR_ACTUALFROMREVISIONID FOREIGN KEY(ACTUALFROMREVISIONID) REFERENCES MODIFICATIONS(ID);
ALTER TABLE GADGETOAUTHACCESSTOKENS ADD CONSTRAINT FK_GADGET_OAUTH_ACCESS_TOKEN_GADGET_OAUTH_CLIENT FOREIGN KEY(GADGETSOAUTHCLIENTID) REFERENCES GADGETOAUTHCLIENTS(ID);
ALTER TABLE RESOURCES ADD CONSTRAINT FK_RESOURCES_BUILDS FOREIGN KEY(BUILDID) REFERENCES BUILDS(ID) ON DELETE CASCADE;
ALTER TABLE PIPELINEMATERIALREVISIONS ADD CONSTRAINT FK_PMR_PIPELINE FOREIGN KEY(PIPELINEID) REFERENCES PIPELINES(ID);
ALTER TABLE MODIFICATIONS ADD CONSTRAINT FK_MODIFICATIONS_PIPELINEID FOREIGN KEY(PIPELINEID) REFERENCES PIPELINES(ID);
ALTER TABLE PIPELINEMATERIALREVISIONS ADD CONSTRAINT FK_PMR_FROM_REVISION FOREIGN KEY(FROMREVISIONID) REFERENCES MODIFICATIONS(ID);
ALTER TABLE BUILDS ADD CONSTRAINT FK_BUILDS_STAGES FOREIGN KEY(STAGEID) REFERENCES STAGES(ID) ON DELETE CASCADE;
ALTER TABLE BUILDSTATETRANSITIONS ADD CONSTRAINT FK_BUILDTRANSITIONS_STAGES FOREIGN KEY(STAGEID) REFERENCES STAGES(ID);
ALTER TABLE GADGETOAUTHAUTHORIZATIONCODES ADD CONSTRAINT FK_GADGET_OAUTH_AUTHORIZATION_CODE_GADGET_OAUTH_CLIENT FOREIGN KEY(GADGETSOAUTHCLIENTID) REFERENCES GADGETOAUTHCLIENTS(ID);
ALTER TABLE OAUTHAUTHORIZATIONS ADD CONSTRAINT FK_OAUTH_AUTHORIZATION_OAUTH_CLIENT FOREIGN KEY(OAUTHCLIENTID) REFERENCES OAUTHCLIENTS(ID);
ALTER TABLE PIPELINEMATERIALREVISIONS ADD CONSTRAINT FK_PMR_MATERIALID FOREIGN KEY(MATERIALID) REFERENCES MATERIALS(ID);
ALTER TABLE PIPELINEMATERIALREVISIONS ADD CONSTRAINT FK_PMR_TO_REVISION FOREIGN KEY(TOREVISIONID) REFERENCES MODIFICATIONS(ID);
ALTER TABLE BUILDSTATETRANSITIONS ADD CONSTRAINT FK_BUILDSTATETRANSITIONS_BUILDS FOREIGN KEY(BUILDID) REFERENCES BUILDS(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICATIONFILTERS ADD CONSTRAINT FK_NOTIFICATIONFILTERS_USERS FOREIGN KEY(USERID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_BUILDS FOREIGN KEY(BUILDID) REFERENCES BUILDS(ID) ON DELETE CASCADE;
