package in.ashwanthkumar.gocd.database.mysql5.migration;

public class IdentityColumns implements DDLPatch {
    @Override
    public boolean shouldPatch(String line) {
        return line.contains("GENERATED BY DEFAULT AS IDENTITY");
    }

    @Override
    public String patch(String line) {
        return line.replace("GENERATED BY DEFAULT AS IDENTITY (START WITH 1)", "NOT NULL AUTO_INCREMENT");
    }
}
